In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("laptops_Raw.csv")
df.head(2)

,Brand:,Product name,Processor,Video graphics,Video graphics Memorey,RAM,Hard drive,Display,Display Resolution,Display Refresh Rate,...,Processor Generation,Processor Details,Product number,Power supply type,Laptop Color,Finger Print,SUPPORT SSD M2,Pointing device,Optical drive,Series :
0,MSI,Titan 18 HX Dragon Edition Norse Myth A2XWJG,Intel Core Ultra 9 285HX,Nvidia GeForce RTX 5090 24GB,24GB GDDR7,96GB DDR5 6400MHz 48GB*2,"6TB, 2TB NVMe PCIe Gen5x4 SSD w/o DRAM + 2TB N...","18"" 16:10 UHD+ (3840x2400), MiniLED, 120Hz, 10...",3840x2400,120 Hz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MSI,Katana 15 HX 14XWGK,Intel Core i9-14900HX,Nvidia GeForce RTX 5070 8GB,8GB GDDR7,16GB DDR5 8GB*2,1TB NVMe PCIe SSD Gen4x4,"15.6"" QHD (2560*1440), 165Hz DCI-P3 100% typical",2560*1440,165 HZ,...,14th generation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail(2)

,Brand:,Product name,Processor,Video graphics,Video graphics Memorey,RAM,Hard drive,Display,Display Resolution,Display Refresh Rate,...,Processor Generation,Processor Details,Product number,Power supply type,Laptop Color,Finger Print,SUPPORT SSD M2,Pointing device,Optical drive,Series :
1031,NaN,M7600QC-OLED007T,AMD Ryzen™ 7-5800H,NVIDIA® GeForce® RTX™ 3050,4GB,"16GB DDR4 on board, Memory Max Up to:32GB","1TB SSD, M.2 NVMe™ PCIe® 3.0","16"" Inch OLED 4K, 16:10 aspect ratio, 0.2ms re...",3840 x 2400,NaN,...,NaN,"8-core/16-thread, 20MB cache, up to 4.4 GHz ma...",90NB0V81-M00690,"ø4.5, 120W AC Adapter, Output: 20V DC, 6A, 120...",NaN,NaN,NaN,NaN,NaN,NaN
1032,NaN,GA401QM-K2040T,AMD Ryzen™ 9-5900HS,NVIDIA® GeForce RTX™ 3060,6GB GDDR6,"16GB, 8GB DDR4 on board + 8GB DDR4-3200 SO-DIMM",1TB M.2 NVMe™ PCIe® 3.0 SSD,14''Inch WQHD (2560 x 1440) 16:9 anti-glare di...,WQHD 2560 x 1440,120 Hz,...,NaN,"8-core/16-thread, 20MB cache, up to 4.6 GHz ma...",90NR05S3-M001A0,"ø6.0, 180W AC Adapter",NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(df.shape)

(1033, 30)

In [9]:
print(df.columns)

Index(['Brand:', 'Product name', 'Processor', 'Video graphics',
       'Video graphics Memorey', 'RAM', 'Hard drive', 'Display',
       'Display Resolution', 'Display Refresh Rate', 'Operating System',
       'Keyboard', 'Battery', 'Webcam', 'Connections', 'Dimensions', 'Weight',
       'Colors', 'Warranty', 'Price', 'Processor Generation',
       'Processor Details', 'Product number', 'Power supply type',
       'Laptop Color', 'Finger Print', 'SUPPORT SSD M2', 'Pointing device',
       'Optical drive', 'Series :'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1033 entries, 0 to 1032
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand:                  977 non-null    object
 1   Product name            1033 non-null   object
 2   Processor               1033 non-null   object
 3   Video graphics          1032 non-null   object
 4   Video graphics Memorey  680 non-null    object
 5   RAM                     1033 non-null   object
 6   Hard drive              1033 non-null   object
 7   Display                 1029 non-null   object
 8   Display Resolution      1013 non-null   object
 9   Display Refresh Rate    680 non-null    object
 10  Operating System        1026 non-null   object
 11  Keyboard                932 non-null    object
 12  Battery                 1003 non-null   object
 13  Webcam                  892 non-null    object
 14  Connections             1009 non-null   object
 15  Dimensions              986 non-null    object
 16  Weight                  993 non-null    object
 17  Colors                  970 non-null    object
 18  Warranty                1033 non-null   object
 19  Price                   1033 non-null   int64
 20  Processor Generation    696 non-null    object
 21  Processor Details       963 non-null    object
 22  Product number          682 non-null    object
 23  Power supply type       104 non-null    object
 24  Laptop Color            13 non-null     object
 25  Finger Print            64 non-null     object
 26  SUPPORT SSD M2          30 non-null     object
 27  Pointing device         25 non-null     object
 28  Optical drive           7 non-null      object
 29  Series :                1 non-null      object
dtypes: int64(1), object(29)
memory usage: 242.2+ KB

In [11]:
df.isnull().sum()

Brand:                      56
Product name                 0
Processor                    0
Video graphics               1
Video graphics Memorey     353
RAM                          0
Hard drive                   0
Display                      4
Display Resolution          20
Display Refresh Rate       353
Operating System             7
Keyboard                   101
Battery                     30
Webcam                     141
Connections                 24
Dimensions                  47
Weight                      40
Colors                      63
Warranty                     0
Price                        0
Processor Generation       337
Processor Details           70
Product number             351
Power supply type          929
Laptop Color              1020
Finger Print               969
SUPPORT SSD M2            1003
Pointing device           1008
Optical drive             1026
Series :                  1032
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1033 entries, 0 to 1032
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand:                  977 non-null    object
 1   Product name            1033 non-null   object
 2   Processor               1033 non-null   object
 3   Video graphics          1032 non-null   object
 4   Video graphics Memorey  680 non-null    object
 5   RAM                     1033 non-null   object
 6   Hard drive              1033 non-null   object
 7   Display                 1029 non-null   object
 8   Display Resolution      1013 non-null   object
 9   Display Refresh Rate    680 non-null    object
 10  Operating System        1026 non-null   object
 11  Keyboard                932 non-null    object
 12  Battery                 1003 non-null   object
 13  Webcam                  892 non-null    object
 14  Connections             1009 non-null   object
 15  Dimensions              986 non-null    object
 16  Weight                  993 non-null    object
 17  Colors                  970 non-null    object
 18  Warranty                1033 non-null   object
 19  Price                   1033 non-null   int64
 20  Processor Generation    696 non-null    object
 21  Processor Details       963 non-null    object
 22  Product number          682 non-null    object
 23  Power supply type       104 non-null    object
 24  Laptop Color            13 non-null     object
 25  Finger Print            64 non-null     object
 26  SUPPORT SSD M2          30 non-null     object
 27  Pointing device         25 non-null     object
 28  Optical drive           7 non-null      object
 29  Series :                1 non-null      object
dtypes: int64(1), object(29)
memory usage: 242.2+ KB

In [13]:
df.describe()

               Price
count    1033.000000
mean    49992.955470
std     36383.605385
min      6499.000000
25%     28777.000000
50%     39799.000000
75%     57877.000000
max    320000.000000

In [14]:
df.isnull().sum()

Brand:                      56
Product name                 0
Processor                    0
Video graphics               1
Video graphics Memorey     353
RAM                          0
Hard drive                   0
Display                      4
Display Resolution          20
Display Refresh Rate       353
Operating System             7
Keyboard                   101
Battery                     30
Webcam                     141
Connections                 24
Dimensions                  47
Weight                      40
Colors                      63
Warranty                     0
Price                        0
Processor Generation       337
Processor Details           70
Product number             351
Power supply type          929
Laptop Color              1020
Finger Print               969
SUPPORT SSD M2            1003
Pointing device           1008
Optical drive             1026
Series :                  1032
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(19)

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
missing = df.isnull().sum()
missing_percentage = (missing / len(df)) * 100
print(missing_percentage)

Brand:                     5.522682
Product name               0.000000
Processor                  0.000000
Video graphics             0.098619
Video graphics Memorey    34.122288
RAM                        0.000000
Hard drive                 0.000000
Display                    0.394477
Display Resolution         1.972387
Display Refresh Rate      34.220907
Operating System           0.690335
Keyboard                   9.960552
Battery                    2.859961
Webcam                    13.905325
Connections                2.366864
Dimensions                 4.536489
Weight                     3.648915
Colors                     5.917160
Warranty                   0.000000
Price                      0.000000
Processor Generation      32.149901
Processor Details          6.903353
Product number            34.319527
Power supply type         89.842209
Laptop Color              98.816568
Finger Print              93.688363
SUPPORT SSD M2            97.041420
Pointing device           97.534517
Optical drive             99.309665
Series :                  99.901381
dtype: float64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.to_csv("laptops_Clean.csv", index=False)