In [59]:
import pandas as pd
import numpy as np
import re
df = pd.read_csv("laptops_Clean.csv")

print("="*50)
print("PROCESSOR")
print("="*50)
print(df["Processor"].unique())

print("\n")

print("="*50)
print("GPU")
print("="*50)
print(df["GPU"].unique())

print("\n")

print("="*50)
print("RAM")
print("="*50)
print(df["RAM"].unique())

print("\n")

print("="*50)
print("STORAGE")
print("="*50)
print(df["Storage"].unique())

print("\n")

print("="*50)
print("REFRESH RATE")
print("="*50)
print(df["Refresh_Rate"].unique())

==================================================
PROCESSOR
==================================================
['Intel Core Ultra 9 285HX' 'Intel Core i9-14900HX' 'Intel Core I5-13420H'
 'Intel Core 7 240H' 'Intel Core 9 270H' 'Intel® Core™ i7-13620H'
 'Intel® Core™ i7-14700HX' 'Intel® Core™ i5-12450HX'
 'Intel® Core™ i5-14450HX' 'Intel® Core™ i5-13420H'
 'Intel® Core™ Ultra 9 285H' 'AMD Ryzen™ AI 9 365'
 'Intel® Core i9-14900HX' 'AMD Ryzen™ AI 7 350'
 'Intel® Core Ultra 9 275HX' 'AMD Ryzen™ 9 8940HX' 'AMD Ryzen 9 9955HX'
 'AMD Ryzen™ 7 260' 'AMD Ryzen 7 8845HS' 'Intel Core Ultra 9 275HX'
 'Intel Core i5-1235U' 'Intel Core i5-13500H' 'Intel® Core™ i7-14650HX'
 'Intel® Core™ i9-14900HX' 'AMD Ryzen™ 7 7435HS' 'Intel® Core™ i7-13700H'
 'AMD Ryzen 7 7435HS' 'Intel Core I5-13450HX' 'Intel Core i7-14650HX'
 'Intel Core 5 210H' 'Intel Core I9-14900HX' 'Intel Core I5-12450HX'
 'Intel Core Ultra 9 185H' 'Intel Core i7-14700HX'
 'Intel® Core™ i5-13450HX' '\u200bIntel Core Ultra 9 275HX'
 'Intel Core Ultra 9 285H' 'Intel® Core™ Ultra 9 275HX'
 'Intel Core I5-12500H' 'Intel Core I7-14700HX' 'AMD Ryzen 7 7735HS'
 'AMD Ryzen 9 8945HS' 'Intel Core i7-13620H' 'Intel Core i5-14450HX'
 'AMD Ryzen AI 9 HX 370' 'Intel Core i5-12450HX' 'Intel Core i5-13420H'
 'Intel Core i7-13700H' 'Intel® Core™ i7-13650HX' 'Intel Core I7-13650HX'
 'Intel® Core™ i5-12450H' 'AMD Ryzen™ 5 8645HS' 'Intel Core i7-13650HX'
 'Intel Core I5-13500H' 'Intel® Core™ i5-13500H' 'Intel Core I7-13620H'
 'Intel Core I7-13700H' 'AMD Ryzen 7 5800H' 'AMD Ryzen™ 7 7445H'
 'Intel® Core i7-13700HX' 'Intel® Core i7-14700HX'
 'Intel® Core i5-12450HX' 'Intel Core Ultra 7 255HX'
 'Intel Core i5-13450HX' 'Intel Core I5 13420H' 'Intel Core i7-12650HX'
 'AMD Ryzen™ 5 7235HS' 'AMD Ryzen™ AI 9 HX 370' 'Intel Core i5-12600HX'
 'Intel Core I9-13980HX' 'Intel Core i7-13700HX' 'Intel Core i9-13900HX'
 'Intel Core I7-11800H' 'Intel Core I9-13900HX' 'Intel Core Ultra 7 155H'
 'Intel Core I7-12700H' 'Intel Core i5-12450H' 'Intel Core I7-14650HX'
 'Intel Core I9-13900H' 'I5-13420H' 'Intel Core i7 -13700HX'
 'Up to Intel® Core™ Ultra 9' 'AMD Ryzen™ 5 7535HS' 'AMD Rayzen 7 7435HS'
 'Intel® Core™ i9-13900HX' 'AMD Ryzen™ 5 5500H'
 'Intel® Core™ Ultra 7 155H' 'AMD Ryzen™ 7 7735HS'
 'Intel® Core™ i7 12650H' 'Intel® Core™ i5 12450H' 'AMD Ryzen 5 5500H'
 'Intel Core i7-12700H' 'AMD Ryzen 5 7535HS' 'AMD Ryzen 5 5600H'
 'AMD Ryzen™ 7 7840HS' 'Intel Core I5-12450H' 'Intel® Core™ Ultra 9'
 'AMD Ryzen 7-5800H' 'Intel Core I5-11400H' 'Intel Core i5-12500H'
 'Intel Core I7-13700HX' 'AMD Ryzen 5-5600H' 'Intel® Core™ i7-12650H'
 'AMD Ryzen™ 5 5600H' 'Intel® Core™ i7-11800H' 'Intel Core I9-12900H'
 'Intel Core i7\u200b\u200b-13700H' 'AMD Ryzen 7-6800HS'
 'AMD Ryzen 7-6800H' 'AMD Rayzen 7-6800H' 'AMD Rayzen 5-6600H'
 'Amd Ryzen 7 5800H' 'Intel® Core™ i7-12700H' 'AMD Ryzen™ 7 5800H'
 'AMD Rayzen 7-6800HS' 'Intel Core I9-11900H' 'AMD Ryzen 9-5900HS'
 'AMD Ryzen 7-7735HS' 'Intel Core I9-12900HK' 'AMD Ryzen 9-7940HS'
 'Intel Core I7 11370H' 'AMD Rayzen 5-5600H' 'Intel Core I7-12650H'
 'Amd Ryzen 5-5600H' 'Intel core I9-13980HX' 'AMD Rayzen 7-4800H'
 'Intel Core I5-10500H' 'Intel Core I7-10750H' 'Amd Ryzen 7-5800H'
 'AMD Ryzen 9-6900HS' 'Amd Ryzen 9-5900HX' 'Intel® Core™ i9-12900H'
 'Intel Core I7-1260P' 'Intel Core I5-1240P' 'Intel Core 17-12700H'
 'Amd Ryzen 7-6800HS' 'Intel Core I7-11370H' 'Amd Ryzen 5-5625U'
 'Amd Ryzen 7-5825U' 'Amd Ryzen 5-4600H' 'AMD Ryzen 7 6800H'
 'Intel Core i7-11800H' 'Intel Core I5-11260H' 'AMD Ryzen 7 4800H'
 'Intel Core i5-11400H' 'AMD Ryzen 7 5800U' 'Intel Core I7-10870H'
 'Intel® Core™ i5-11300H' 'Intel Core I5-11320H' 'Intel Core I9-12950HX'
 'AMD Ryzen 9 6900HX' 'AMD Ryzen 7 3750H' 'Intel Core i7-11370H'
 'Intel Core i5-11300H' 'AMD Ryzen 9 5900HX' 'Intel Core i7-10875H'
 'AMD Ryzen™ 9 5900HX' 'AMD Ryzen™ 9 5900HS' 'Intel Core i9-11900H'
 'Intel Core I5-10300H' 'Amd Ryzen 9- 5900H' 'Intel Core I5-11300H'
 'Intel Core I9-11980HK' 'Intel CoreI7-11800H' 'Intel® Core™ i7-11370H'
 'Amd Ryzen 9-5900HS' 'Intel core I7-11800H' 'Intel core I9-11900H'
 'Intel Core I7 11800H' 'AMD Ryzen™ 7-5800H' 'Intel® Core™ i9-11900H'
 'AMD Ryzen 9-5900HX' 'Intel® Core™ i5-11260H' 'Intel Core i9-11980HK'
 'Amd Ryzen 9 5900Hs' 'Intel® Core™ I7-11370H' 'AMD Ryzen™ 7-4800H'
 'AMD RYZEN 7 5800H' 'Intel® Core™ i7-10750H' 'AMD Ryzen™ 7 4800H'
 'Intel Core I7-10875H' 'Intel Core 7 150U' 'Intel® Core i7-13620H'
 'Intel® Core i5-13420H' 'AMD Ryzen™ 5 8640HS' 'Intel Core i5-1334U'
 'AMD Ryzen 7 5700U' 'Intel® Core™ i3-1315U' 'Intel Core 5 120U'
 'Snapdragon X X1 26 100' 'Snapdragon X Plus X1P 42 100'
 'Intel Core Ultra 7 255H' 'Intel Core i7-1355U' 'AMD Ryzen 5 3450U'
 'Intel Core I5-1235U' 'Intel Core i3-1215U' 'Intel® Core™ i5-1335U'
 'Intel® Core i3-1315U' 'Intel® Core™ i5-1334U' 'Intel Core Ultra 7 155U'
 'Intel Core Ultra 5 225H' 'AMD Ryzen AI 7 350' 'AMD Ryzen 3 7320U'
 'Intel Core i9-13900H' 'Intel Celeron N4020' 'Intel Core I7-1255U'
 'Intel Core i7-1165G7' 'Intel® Core™ i9-13900H' 'Intel Core Ultra 5 125H'
 'Intel Core I3-1305U' 'Snapdragon X Elite' 'Intel Core I3-1215U'
 'Intel Core i3-1315U' 'Intel Core I7-1165G7' 'Intel Core i5-1335U'
 'AMD Ryzen 7 7730U' 'AMD Ryzen 5 7430U' 'Intel® Core™ i3-N305'
 'Intel® Core™ i3-1215U' 'Intel® Core™ Ultra 7 155U' 'AMD Ryzen 3 3250U'
 'Intel® Core™ i7-1255U' 'Intel® Core™ i7-1355U' 'Intel Core i7-1255U'
 'Intel Core i5-1035G1' 'AMD Ryzen 5 7520U' 'Intel® Core™ i5-1235U'
 'Intel® Core™ i5-1135G7' 'AMD Ryzen 5-5625U' 'AMD Ryzen™ 7 3700U'
 'AMD Ryzen 5 7530U' 'Intel Core I5-1340P'
 'Intel® Core™ Ultra 9 Processor 185H' 'AMD Ryzen™ 7 5700U'
 'Intel Core I5-1035G1' 'Intel Core I5-1135G7' 'Intel Core I7-1355U'
 'Intel Core i3- 1115G4' 'Intel Core I3-10110U' 'AMD Ryzen 7-5700U'
 'Intel Core I5-1335U' 'Intel Core I7-10510U' 'Intel Core I7-1195G7'
 'Amd Ryzen 5-5500U' 'AMD Ryzen 5-7520U' 'Intel Core I3-1115G4'
 'Intel Core i5 1135G7' 'AMD Ryzen 5 5500U' 'Intel Core I3-1115G'
 '12th Gen Intel® Core™ i7-1255U' 'AMD Ryzen 5-5500U'
 'Intel Core I3-1005G1' 'Inte Core I7-12700H' 'AMD Ryzen 3 5300U'
 'Intel Core I5-1155G7' 'Intel Core I7-1065G7' 'Amd Ryzen 7-5700U'
 'AMD 3020E' 'Intel Core i5-1135G7' 'AMD Ryzen 7-3700U'
 'Amd Ryzen 3 3250U' 'Intel Core I7-11390H' 'Intel Core i3-10110U'
 'AMD 3020e' 'Intel Core i3-1115G4' 'Intel Core i7-1065G7'
 'AMD Ryzen™ 3 3200U' 'Intel Core i5-11320H' 'Intel Core i7-1185G7'
 'Amd Ryzen 7-4700U' 'Intel Core i3-1125G4' 'Amd Ryzen 5-3450U'
 'Intel® Core™ I7-1165G7' 'Intel® Core™ i7-1165G7' 'Intel core I5-1135G7'
 'Intel Core i3-1005G1' 'Intel Core Ultra 5 125U' 'Intel® Core i5-1235U'
 'Intel® Core i7-1355U' 'Intel® Core™ Ultra 7 265U'
 'Intel Core Ultra 7 265U' 'Intel® Core™ 5 120U' 'Intel Core Ultra 9 288V'
 'Intel Core Ultra 5 235U' 'Intel® Core Ultra 7 155U' 'Intel Core Ultra 5'
 'Intel® Core™ Ultra 5 125U' 'Intel  Core Ultra 7 155U'
 '\u200bIntel Core I5-1335U' 'Snapdragon® X Plus (10 Core)'
 'lntel® Core™ i7-1355U' 'Intel® Core i7-1255U' 'Intel  Core  i7-1355U'
 'Intel Core I5-1145G7' 'Intel core I5-1145G7' 'Intel core i5-1135G7'
 'INTEL CORE i5-1035G1' 'Intel® Core™ i5-10210U' 'AMD Ryzen 9-5980HS'
 'AMD Ryzen™ 9-5900HS']


==================================================
GPU
==================================================
['Nvidia GeForce RTX 5090 24GB' 'Nvidia GeForce RTX 5070 8GB'
 'Nvidia GeForce RTX 4050 6GB' 'NVIDIA(R) GeForce RTX(TM) 5050'
 'Nvidia GeForce RTX 5060 8GB' 'Nvidia GeForce RTX 5060'
 'Nvidia GeForce RTX 5050' 'NVIDIA® GeForce RTX™ 3050'
 'NVIDIA® GeForce RTX™ 4050' 'Nvidia GeForce RTX 3050 6GB'
 'NVIDIA® GeForce RTX™ 5070' 'NVIDIA® GeForce RTX™ 5070 Laptop GPU'
 'NVIDIA® GeForce RTX™ 5080' 'NVIDIA® GeForce RTX™ 5070 Ti'
 'NVIDIA® GeForce RTX™ 5050' 'NVIDIA® GeForce RTX™ 4050 6GB'
 'NVIDIA® GeForce RTX™ 5090 24GB' 'Nvidia GeForce RTX 2050 4GB'
 'NVIDIA® GeForce RTX™ 5060 Laptop GPU' 'NVIDIA® GeForce RTX™ 5060'
 'NVIDIA® GeForce RTX™ 4050 6GB GDDR6' 'Nvidia GeForce RTX 4060 8GB'
 'Nvidia GeForce RTX 5050 8GB' 'NVIDIA® GeForce RTX™ 2050'
 'Nvidia GeForce RTX 3050' 'Nvidia GeForce RTX 5070 Ti 12GB'
 'Nvidia GeForce RTX 5070Ti 12GB' 'Nvida GeForce RTX 4060 8GB'
 'Nvidia Geforce RTX 4070' 'Nvidia GeForce RTX 4070 8GB'
 'Nvidia GeForce RTX 5080 16GB' 'Nvidia GeForce RTX 4090 16GB'
 'GeForce RTX™ 5070 Ti' 'Nvidia GeForce RTX 5080'
 'Nvidia GeForce RTX™ 5090' 'Nvidia GeForce RTX 5070'
 'NVIDIA® GeForce RTX™ 4060 8GB' 'NVIDIA® GeForce RTX™ 4060'
 'Nvidia GeForce RTX 4070 8GB\u200b' 'NVIDIA® GeForce RTX™ 3050 6GB'
 'Nvidia GeForce RTX 4060' 'NVIDIA® GeForce RTX™ 3050 6G'
 'NVIDIA® GeForce RTX™ 4070' 'NVIDIA® GeForce RTX™ 3050 6GB GDDR6'
 'Nvida GeForce RTX 4050 6GB' 'NVIDIA GeForce RTX RTX 3050Ti 4GB'
 'NVIDIA® GeForce RTX™ 5070, 8GB' 'NVIDIA® GeForce RTX™ 5060, 8GB'
 'NVIDIA® GeForce RTX™ 2050 Laptop GPU'
 'NVIDIA® GeForce RTX™ 5090 Laptop GPU'
 'NVIDIA® GeForce RTX™ 5070 Ti 12GB' 'Nvidia GeForce RTX 3050 4GB'
 'Nvida GeForce RTX 3050' 'Nvidia GeForce RTX 5070 Ti'
 'Nvidia GeForce RTX 4080 12GB' 'Nvidia GeForce RTX 3070 8GB'
 'AMD Radeon RX 6600M 8GB' 'NVIDIA® GeForce RTX™ 3050 4GB'
 'NVIDIA® GeForce RTX™ 4070 8GB' 'NVIDIA® GeForce RTX™ 4070 8GB GDDR6'
 'NVIDIA GeForce RTX 4060' 'NVIDIA GeForce RTX 4080'
 'NVIDIA® GeForce RTX™ 4070 Laptop GPU 8GB GDDR6'
 'NVIDIA® GeForce RTX™ 4090' 'NVIDIA® GeForce RTX™ 4070 Laptop GPU'
 'NVIDIA® GeForce RTX™ 4060 Laptop GPU' 'NVIDIA® GeForce RTX™'
 'NVIDIA® GeForce RTX™ 4090 16GB' 'NVIDIA® GeForce RTX™ 3050 4GB6'
 'Nvidia GeForce RTX3050 4GB' 'NVIDIA® GeForce RTX™ 2050 4GB'
 'NVIDIA® GeForce RTX™ 3060 6GB' 'NVIDIA® GeForce RTX™ 4050  6GB'
 'NVIDIA® GeForce RTX™ 3060' 'NVIDIA® GeForce RTX™ 3050 Ti'
 'Nvidia GeForce RTX 3060 6GB' 'NVIDIA® GeForce® GTX 1650'
 'NVIDIA® GeForce RTX™ 4080' 'Nvidia GeForce RTX 4070'
 'Nvidia GeForce RTX 4090' 'Nvidia GeForce RTX 4050'
 'Nvidia® GeForce® RTX™ 3050 4GB' 'Nvidia GeForce GTX 1650 4GB'
 'NVIDIA® GeForce® GTX 1650 4GB' 'NVIDIA GeForce RTX 4060 8GB'
 'AMD Radeon™ RX 6500M 4GB' 'NVIDIA® GeForce RTX™ 2050 4GB GDDR6'
 'NVIDIA® GeForce RTX™ 3050Ti 4GB' 'NVIDIA GeForce GTX 1650 4GB'
 'Nvidia GeForce GTX 1650' 'NVIDIA® GeForce RTX™ 3050 Ti 4GB'
 'NVIDIA® GeForce RTX™ 3080 16GB' 'NVIDIA® GeForce RTX™ 3070 8GB'
 'AMD Radeon™ RX 6500M Graphics' 'NVIDIA® GeForce RTX™ 3070 Ti 8GB'
 'AMD Radeon™ RX 6700S' 'NVIDIA GeForce RTX™ 3060, 6GB'
 'NVIDIA® GeForce RTX™ 3070Ti 8GB' 'NVIDIA® GeForce RTX™ 3080Ti'
 'NVIDIA® GeForce RTX™ 3080 Ti 16GB' 'NVIDIA GeForce RTX 3070 8GB'
 'Nvidia GeForce RTX 3070Ti 8GB' 'NVIDIA® GeForce RTX™ 3080 8GB'
 'NVIDIA® GeForce RTX™ 4080 12GB' 'NVIDIA GeForce RTX 3050 6GB'
 'Nvidia GeForce RTX 3050Ti 4GB' 'NVIDIA GeForce RTX 3050 4GB'
 'Nvidia GeForce RTX3060 6GB' 'NVIDIA® GeForce RTX™ 3050Ti'
 'NVIDIA® GeForce® GTX 1650 4GB GDDR6'
 'NVIDIA® GeForce® RTX™ 3050 Laptop GPU 4GB GDDR6'
 'NVIDIA® GeForce RTX™ 3070Ti' 'NVIDIA® GeForce® RTX™ 3060 Laptop GPU 6GB'
 'NVIDIA® GeForce® RTX™ 3060 Laptop GPU 6GB GDDR6'
 'NVIDIA® GeForce® RTX™ 3060 6GB' 'NVIDIA® GeForce RTX™ 3070 Ti'
 'NVIDIA GeForce RTX 4080 12GB' 'Nvidia GeForce RTX 3060'
 'NVIDIA® GeForce RTX™ 3050TI 4GB'
 'NVIDIA® GeForce RTX™ 3060 Laptop GPU, 1752MHz at 140W (1702MHz Boost Clock+50MHz OC, 115W+25W Dynamic Boost), 6GB GDDR6'
 'NVIDIA® GeForce RTX™ 3050 Ti Laptop GPU 4GB GDDR6'
 'Nvidia GeForce RTX 3050TI 4GB' 'NVIDIA® GeForce GTX™ 1650 4GB'
 'NVIDIA GeForce GTX1650 4GB'
 'NVIDIA® GeForce® GTX 1650 Laptop GPU (4GB GDDR6 dedicated)'
 'Nvidia GeForce RTX3050TI 4GB GDDR6 GPU Boost Clock Up to 1485MHz Maximum Graphics Power Up to 75 W'
 'Nvidia® GeForce® RTX™ 3050' 'NVIDIA GeForce RTX™ 3060 6GB'
 'NVIDIA GeForce RTX 3050 Ti 4GB' 'NVIDIA® GeForce RTX™ 3050 Ti 4GB GDDR6'
 'NVIDIA GeForce RTX 3060 6GB GDDR6' 'NVIDIA® GeForce RTX™ 3050 4GB GDDR6'
 'NVIDIA GeForce RTX 3050' 'AMD Radeon™ RX6700M 10GB'
 'NVIDIA® GeForce RTX™ 3070 Laptop GPU,With ROG Boost up to 1390MHz at 80W (85W with Dynamic Boost),8GB GDDR6'
 'Nvidia GeForce RTX 3050 Ti 4GB' 'NVIDIA GeForce RTX 3060 6GB'
 'NVIDIA® GeForce RTX™ 3080 Ti Laptop GPU 16GB'
 'NVIDIA® GeForce® GTX 1650, 4GB' 'Nvidia GeForce RTX 3070 Ti 8GB'
 'NVIDIA GeForce RTX 3070 8GB GDDR6' 'NVIDIA GeForce RTX 3070'
 'NVIDIA GeForce RTX 3050 Ti' 'Nvidia GeForce RTX 3080'
 'NVIDIA GeForce RTX 3080'
 'NVIDIA® GeForce® GTX 1650 Laptop GPU (4 GB GDDR6 dedicated)'
 'Nvidia® GeForce® RTX™ 3060 6GB' 'NVIDIA GeForce RTX™ 3070 8GB'
 'NVIDIA GeForce GTX 1650' 'NVIDIA® GeForce® GTX1650 4G'
 'DIA® GeForce RTX™ 3050 Ti 4GB' 'NVIDIA® GeForce® RTX™ 3080'
 'NVIDIA GeForce RTX 3050Ti 4GB' 'NVIDIA® GeForce® GTX 1650 Ti 4GB'
 'NVIDIA GeForce RTX 3060' 'NVIDIA® GeForce RTX™ 3050TI'
 'NVIDIA GeForce RTX 3080 16GB' 'Nvidia GeForce RTX3080 16GB'
 'NVIDIA GeForce RTX 3050Ti' 'NVIDIA® GeForce RTX™3080 16 GB'
 'Nvidia GeForce RTX 3080 8GB' 'Nvidia GeForce RTX 3070 Max-Q 8GB'
 'NVIDIA® GeForce® RTX™ 3050' 'Nvidia GeForce RTX 3070'
 'Nvidia\xa0GeForce\xa0RTX\xa03060 6GB'
 'NVIDIA®\xa0GeForce\xa0RTX™\xa03050\xa0Ti Laptop GPU'
 'NVIDIA®\xa0GeForce\xa0RTX™\xa03080 16GB' 'NVIDIA GeForce RTX™ 3080'
 'NVIDIA®\xa0GeForce\xa0RTX™\xa03050' 'NVIDIA®\xa0GeForce\xa0RTX™\xa03070'
 'NVIDIA®\xa0GeForce\xa0RTX™\xa03080'
 'NVIDIA®\xa0GeForce\xa0RTX™\xa03060 Laptop GPU'
 'NVIDIA®\xa0GeForce\xa0RTX™\xa03050 Laptop GPU'
 'NVIDIA® GeForce® GTX 1650TI' 'Nvidia® GeForce® RTX™ 3060, 6 GB, GDDR6'
 'NVIDIA® GeForce® RTX 3050Ti' 'Nvidia® GeForce® RTX™ 3050, 4GB, GDDR6'
 'NVIDIA GeForce GTX 1650 Ti 4 GB' 'NVIDIA GeForce RTX 2060'
 'NVIDIA GeForce GTX 1650TI 4 GB' 'Intel Graphics'
 'Integrated Intel® UHD Graphics' 'Integrated AMD Radeon™ 760M Graphics'
 'Intel® UHD Graphics' 'Intel UHD Graphics'
 'Integrated AMD Radeon™ Graphics'
 'Integrated Intel® Iris® Xe Graphics Functions as UHD Graphics'
 'AMD Radeon Graphics' 'Integrated Intel UHD Graphics'
 'Qualcomm Adreno GPU' 'Intel Arc Graphics' 'Intel® Graphics'
 'AMD Radeon™ 890M Graphics' 'Nvidia GeForce MX570 A'
 'AMD Radeon Vega 8 Graphics' 'Intel Iris Xe Graphics'
 'Intel® Iris® Xe Graphics' 'Intel® Iris® Xᶱ Graphics'
 'AMD Radeon 890M Graphics'
 'Integrated Intel Iris Xe Graphics Functions as UHD Graphics'
 'Nvidia GeForce MX450 2GB' 'Intel UHD Graphics 600'
 'Intel Iris Xᵉ Graphics' 'AMD Radeon™ Graphics'
 'Integrated Intel® Graphics' 'NVIDIA® GeForce MX550 2GB GDDR6'
 'Nvidia GeForce MX570 2GB' 'NVIDIA® Geforce RTX™ 2050'
 'NVIDIA® GeForce MX550 2GB' 'NVIDIA® GeForce® MX570'
 'NVIDIA GeForce MX550' 'NVIDIA® GeForce® MX550'
 'AMD Radeon™ RX Vega 10 Graphics' 'Intel® Iris Xe Graphics'
 'Intel® Arc™ Graphics' 'NVIDIA GeForce MX330 2GB'
 'Intel® Iris® Xe graphics' 'Intel® Iris® Xᵉ Graphics'
 'NVIDIA® GeForce® MX350 2GB' 'NVIDIA® GeForce® MX450 2GB'
 'NVIDIA® GeForce® MX330 2GB' 'NVIDIA® GeForce MX350 2GB'
 'Nvidia GeForce MX550 2GB' 'NVIDIA GeForce MX350 2GB'
 'AMD Radeon RX640 2GB' 'Nvidia GeForce MX350 2GB' 'Intel Iris Xe'
 'Nvidia GeForce MX 330 2GB' 'Nvidia GeForce MX450'
 'Integrated,  AMD Radeon™ Graphics' 'AMD Radeon RX Vega 10 Graphics'
 'NVIDIA GeForce MX350' 'NVIDIA GeForce MX450 2GB'
 'Integrated AMD Radeon Graphics' 'Intel Iris Plus Graphics'
 'AMD Radeon™ Vega 3 Graphics' 'Nvidia GeForce MX350 2GB GDDR5'
 'Intel Iris Xe graphics' 'NVIDIA® GeForce® MX330, 2GB GDDR5'
 'Nvidia GeForce MX330 2GB'
 'NVIDIA GeForce MX350 with 2GB GDDR5 graphics memory' 'Intel® Iris® Xe'
 'Integrated Intel Iris® Xe Graphics' 'NVIDIA GeForce MX350 2GB GDDR5' nan
 'Integrated Intel® graphics' 'Integrated Intel Graphics'
 'Integrated IntelArc'
 'Integrated Intel® Arc™ 140T GPU Functions as Intel Graphics'
 'Intel Integrated Iris Xe' 'Integrated Intel® Arc'
 'NVIDIA® GeForce MX550' 'Nvidia GeForce MX550' 'Integrated Intel Arc'
 'Integrated Intel Iris Xe or UHD graphics' 'Intel Integrated Iris Xe UHD'
 'Integrated Intel graphics' 'Integrated Intel® Arc™ Graphics'
 'Nvidia GeForce MX550 2GB GDDR6' 'NVIDIA® GeForce MX450 2GB'
 'Qualcomm® Adreno™ GPU' 'NVIDIA® GeForce® MX550 2GB'
 'Intel Integrated Graphics' 'Inte Iris Xe Graphics'
 'NVIDIA GeForce MX570 2GB' 'NVIDIA® GeForce® MX570 2GB'
 'NVIDIA® GeForce® MX450 2GB GDDR6' 'AMD Radeon™ 630'
 'NVIDIA GeForce MX230 2GB' 'NVIDIA®\xa0GeForce\xa0RTX™\xa03060']


==================================================
RAM
==================================================
['96GB DDR5 6400MHz 48GB*2' '16GB DDR5 8GB*2' '8 GB DDR5-SDRAM'
 '16GB, 2x8GB, DDR5, 5600 MT/s ( 5200 MT/s with Intel Core 5 CP U)'
 '16GB, 2x8GB, DDR5, 5600 MT/s' '32GB, 2x16GB, DDR5, 5600 MT/s'
 '16 GB DDR4-3200 MT/s (1 x 16 GB)'
 '16 GB DDR5-5600 MT/s (2 x 8 GB) Transfer rates up to 5600 MT/s. 2 x 8 GB'
 '16 GB DDR4-3200 MT/s (1 x 16 GB) Transfer rates up to 3200 MT/s. 1 x 16 GB'
 '1x 16GB SO-DIMM DDR5-4800'
 '8 GB DDR4-3200 MT/s (1 x 8 GB) Transfer rates up to 3200 MT/s. 1 x 8 GB'
 '32 GB DDR5-5600 MT/s (2 x 16 GB)' '1x 16GB SO-DIMM DDR5-5600'
 '32GB LPDDR5X 7500 on board(Actual memory speeds may vary by CPU configuration.)'
 '2x 32GB CSODIMM DDR5-6400' '16GB DDR5-5200 SO-DIMM'
 '16GB DDR5-5600 SO-DIMM' '16GB*2 LPDDR5X 7500 on board, Max Capacity'
 '16GB 8GB*2 LPDDR5X 7500 on board' '32GB' '32GB DDR5-6400'
 '64GB DDR5 6400MHz 32GB*2' '8GB DDR4 SDRAM'
 '8 GB DDR4-3200 MT/s (1 x 8 GB)' '16GB 2x 8GB' 'DDR5 8GB*2'
 '16GB 8GB*2 DDR5' '12GB SO-DIMM DDR5-4800' '16 GB DDR5-5200 MT/s'
 '1x 12GB SO-DIMM DDR5-4800' '16GB, 1x16GB, DDR5, 4800MT/s'
 '8 GB DDR4-3200 MT/s' '32GB 2x 16GB SO-DIMM DDR5-5600' '16GB DDR5'
 '8GB DDR4' '32GB DDR5-5600 SO-DIMM' '16GB Ram' '16GB RAM'
 '32GB Ram DDR5-5600' '16GB DDR5-6400' '16 GB DDR5-5600 MT/s (2 x 8 GB)'
 '32GB Ram' '32GB 2 x 16 Up to DDR5-6400' '32GB 2 x 16 DDR5-6400'
 '2x 12GB SO-DIMM DDR5-4800' '64GB DDR5-5600 SO-DIMM' '32GB LPDDR5X 7467'
 '16 GB DDR5-5200 MT/s (2 x 8 GB)' '16GB 2x 8GB SO-DIMM DDR5-5600'
 '8GB DDR5-5600 SO-DIMM' '8GB DDR4 on board' '16GB'
 '16 GB DDR4-3200 MT/s (2 x 8 GB)'
 '16GB 8GB*2 LPDDR5X 7500 on board, Max Capacity:16GB' '16 GB RAM'
 '16GB DDR5 5600MB/s' '16 GB DDR5-5600 MT/s' '16GB,2X8,5600,DDR5,'
 '8GB (8G*1) DDR4 3200MHz' '16 GB' '16GB DDR5-5200 MT/s (2 x 8 GB)'
 '8 GB DDR5-5600 MT/s (1 x 8 GB)' '16GB DDR5-5200 2 Slots'
 '16 GB DDR5-5200 MHz RAM' '16GB, 2x8GB, DDR5, 4800MHz'
 '16GB 2x8GB SO-DIMM DDR5-5200' '16GB DDR4 3200MHz'
 '16 GB DDR5-5200 MHz RAM (2 x 8 GB)' '2x 16GB SO-DIMM DDR5-5600'
 '32GB DDR5-5200 SO-DIMM x 2' '16GB 8GB*2 LPDDR5X 7500 on board,'
 '24GB 2x 12GB SO-DIMM DDR5-4800' '8GB' 'DDR5 6400MHz 32GB*2'
 '16GB DDR5 SO-DIMM' '32GB (16GB DDR5-5600 SO-DIMM, *2)' '16GB DDR4'
 '64GB LPDDR5X on board' '16GB 8GB DDR4 on board 8GB DDR4 SO-DIMM'
 '16GB DDR4-3200 MT/s (2 x 8 GB)' '16GB DDR5-5600 2*8' '64GB'
 '16 GB DDR5-4800 MT/s (2 x 8 GB)' '32GB DDR5, 2x16GB, 4800MT/s'
 '16 GB DDR5-5200 MT/s (2 x 8' '16GB 2x 8GB SO-DIMM DDR4-3200'
 '16GB Soldered LPDDR5x-7467' '16GB DDR4-3200 SO-DIMM' '8GB DDR4-3200'
 '16GB DDR4-3200'
 '16 GB DDR5-5200 MT/s (2 x 8 GB)  (Transfer rates up to 5200 MT/s.)'
 '32 GB DDR5-5600 MHz RAM (2 x 16 GB)' '32GB 16GB*2 LPDDR5X on board'
 '16GB SO-DIMM DDR5-4800' '32GB Soldered LPDDR5x-7467'
 '2x 8GB SO-DIMM DDR5-4800' '16GB 2x 8GB SO-DIMM DDR5-4800'
 '32GB 16GB DDR5 x 2' '16GB - DDR5' '16GB  2*8 DDR5' '16GB 2*8 DDR5'
 '32GB 16GB x2 DDR5' '16 GB DDR5-4800 MT/s'
 '16 GB LPDDR5, 4800 MT/s (onboard)' 'DDR4 16GB' '16GB DDR5-4800 SO-DIMM'
 '16GB 8GB DDR5-4800 SO-DIMM x 2,' '16GB (8GB DDR5-4800 SO-DIMM *2)'
 '16GB 8GB DDR5-4800 SO-DIMM x 2' '32GB 16GB*2 DDR5'
 '16GB 8GB DDR5-4800 SO-DIMM *2' '16 GB DDR4-3200 MT/s'
 '8GB SO-DIMM DDR4-3200' '16GB SO-DIMM DDR5-5600' '16GB, 2x8GB, DDR5'
 '8GB Ram DDR4-3200' '16GB SO-DIMM DDR5' '8GB DDR5-4800 SO-DIMM'
 '8GB DDR4-3200 MT/s (1 x 8 GB)' '8 GB DDR4-3200 MHz RAM (2 x 4 GB)'
 '1x 8GB SO-DIMM DDR5-4800' '16GB DDR5-5200' '1x 8GB SO-DIMM DDR4-3200'
 '16GB DDR5-4800 MHz RAM (2 x 8 GB)' '16 GB DDR4-3200 MHz RAM (2 x 8 GB)'
 '32 GB DDR5-5600 MHz' '16 GB DDR5-4800 MHz RAM (2 x 8 GB)'
 '16GB,2X8,4800,DDR5,' '8 GB DDR4-3200 MHz RAM (1 x 8 GB)'
 '16GB  8GB DDR5-5600 SO-DIMM, the memory speed of the systems vary by CPU SPEC x 2'
 '32GB 16GB DDR5-5600 SO-DIMM, the memory speed of the systems vary by CPU SPEC x 2'
 '32GB DDR5 16GB*2' '64GB DDR5 32GB*2' '8GB DDR5-4800'

In [60]:
df = pd.read_csv("laptops_Clean.csv")
print(df.shape)
df.head()

(1014, 30)

,Brand,Product_Name,Processor,GPU,GPU_Memory,RAM,Storage,Display,Display_Resolution,Refresh_Rate,...,Processor_Generation,Processor_Details,Product_Number,Power_Supply,Laptop_Color,Fingerprint,SSD_M2_Support,Pointing_Device,Optical_Drive,Series
0,MSI,Titan 18 HX Dragon Edition Norse Myth A2XWJG,Intel Core Ultra 9 285HX,Nvidia GeForce RTX 5090 24GB,24GB GDDR7,96GB DDR5 6400MHz 48GB*2,"6TB, 2TB NVMe PCIe Gen5x4 SSD w/o DRAM + 2TB N...","18"" 16:10 UHD+ (3840x2400), MiniLED, 120Hz, 10...",3840x2400,120 Hz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MSI,Katana 15 HX 14XWGK,Intel Core i9-14900HX,Nvidia GeForce RTX 5070 8GB,8GB GDDR7,16GB DDR5 8GB*2,1TB NVMe PCIe SSD Gen4x4,"15.6"" QHD (2560*1440), 165Hz DCI-P3 100% typical",2560*1440,165 HZ,...,14th generation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Acer,NITRO V15-ANV15-51-51H9,Intel Core I5-13420H,Nvidia GeForce RTX 4050 6GB,6GB GDDR6,8 GB DDR5-SDRAM,512 GB SSD,15.6'' Inch FHD IPS LED backlight aspect ratio...,1920x1080,144 Hz,...,13th generation,"8C (4P + 4E) / 12T, P-core 2.1 / 4.6GHz, E-cor...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dell,Alienware 16 Aurora AC16250,Intel Core 7 240H,NVIDIA(R) GeForce RTX(TM) 5050,8 GB GDDR7,"16GB, 2x8GB, DDR5, 5600 MT/s ( 5200 MT/s with ...",512GB M.2 PCIe NVMe SSD,"16"" WQXGA 120Hz, 300 nits, ComfortView Plus, 1...",2560 x 1600,120 Hz,...,NaN,"240H (24MB cache, 1 0 cores, 1.80 to 5.20 GHz ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dell,Alienware 16 Aurora AC16250,Intel Core 9 270H,Nvidia GeForce RTX 5060 8GB,8GB GDDR7,"16GB, 2x8GB, DDR5, 5600 MT/s",1TB M.2 PCIe NVMe SSD,"16"" WQXGA 120Hz, 300 nits, ComfortView Plus, 1...",2560 x 1600,120 Hz,...,NaN,"24MB cache, 14 cores, 2.00 to 5.80 GHz P-Core",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df = df[[
    "Brand",
    "Processor",
    "GPU",
    "RAM",
    "Storage",
    "Display_Resolution",
    "Refresh_Rate",
    "Price"
]]
df.head(2)

,Brand,Processor,GPU,RAM,Storage,Display_Resolution,Refresh_Rate,Price
0,MSI,Intel Core Ultra 9 285HX,Nvidia GeForce RTX 5090 24GB,96GB DDR5 6400MHz 48GB*2,"6TB, 2TB NVMe PCIe Gen5x4 SSD w/o DRAM + 2TB N...",3840x2400,120 Hz,320000
1,MSI,Intel Core i9-14900HX,Nvidia GeForce RTX 5070 8GB,16GB DDR5 8GB*2,1TB NVMe PCIe SSD Gen4x4,2560*1440,165 HZ,79999

In [62]:
def extract_ram(text):
    text = str(text).upper()

    # Case 1: 16GB, 8 GB, 32GB
    match = re.search(r'(\d+)\s*GB', text)
    if match:
        return int(match.group(1))

    # Case 2: 2*8, 2x8
    match = re.search(r'(\d+)\s*[*X]\s*(\d+)', text)
    if match:
        return int(match.group(1)) * int(match.group(2))

    return np.nan
df["RAM_GB"] = df["RAM"].apply(extract_ram)

df[["RAM", "RAM_GB"]].head(10)

                                                 RAM  RAM_GB
0                           96GB DDR5 6400MHz 48GB*2      96
1                                    16GB DDR5 8GB*2      16
2                                    8 GB DDR5-SDRAM       8
3  16GB, 2x8GB, DDR5, 5600 MT/s ( 5200 MT/s with ...      16
4                       16GB, 2x8GB, DDR5, 5600 MT/s      16
5                      32GB, 2x16GB, DDR5, 5600 MT/s      32
6  16GB, 2x8GB, DDR5, 5600 MT/s ( 5200 MT/s with ...      16
7                   16 GB DDR4-3200 MT/s (1 x 16 GB)      16
8  16 GB DDR5-5600 MT/s (2 x 8 GB) Transfer rates...      16
9  16 GB DDR4-3200 MT/s (1 x 16 GB) Transfer rate...      16

In [63]:
def extract_storage(text):
    text = str(text).upper()

    total_storage = 0

    tb_matches = re.findall(r'(\d+)\s*TB', text)
    gb_matches = re.findall(r'(\d+)\s*GB', text)

    for tb in tb_matches:
        total_storage += int(tb) * 1024

    for gb in gb_matches:
        total_storage += int(gb)

    return total_storage


df["Storage_GB"] = df["Storage"].apply(extract_storage)

df[["Storage", "Storage_GB"]].head(10)

                                             Storage  Storage_GB
0  6TB, 2TB NVMe PCIe Gen5x4 SSD w/o DRAM + 2TB N...       10240
1                           1TB NVMe PCIe SSD Gen4x4        1024
2                                         512 GB SSD         512
3                            512GB M.2 PCIe NVMe SSD         512
4                              1TB M.2 PCIe NVMe SSD        1024
5                              1TB M.2 PCIe NVMe SSD        1024
6                              1TB M.2 PCIe NVMe SSD        1024
7                    512 GB PCIe® Gen4 NVMe™ M.2 SSD         512
8                512 GB PCIe® Gen4 NVMe™ TLC M.2 SSD         512
9                    512 GB PCIe® Gen4 NVMe™ M.2 SSD         512

In [64]:
def extract_refresh_rate(text):
    text = str(text).upper()

    match = re.search(r'(\d+)', text)

    if match:
        return int(match.group(1))

    return 60


df["Refresh_Hz"] = df["Refresh_Rate"].apply(extract_refresh_rate)

df[["Refresh_Rate", "Refresh_Hz"]].head(10)

  Refresh_Rate  Refresh_Hz
0       120 Hz         120
1       165 HZ         165
2       144 Hz         144
3       120 Hz         120
4       120 Hz         120
5       120 Hz         120
6        120Hz         120
7       144 Hz         144
8       144 Hz         144
9       144 Hz         144

In [65]:
cpu_scores = {
    "ULTRA 9": 10,
    "CORE 9": 10,
    "I9": 10,
    "RYZEN 9": 10,

    "ULTRA 7": 8,
    "CORE 7": 8,
    "I7": 8,
    "RYZEN 7": 8,

    "ULTRA 5": 6,
    "CORE 5": 6,
    "I5": 6,
    "RYZEN 5": 6,

    "I3": 4,
    "RYZEN 3": 4,

    "N100": 2,
    "N95": 2,
    "PENTIUM": 2,
    "CELERON": 1
}


def get_cpu_score(cpu):
    cpu = str(cpu).upper()

    for key, score in cpu_scores.items():
        if key in cpu:
            return score

    return 5


df["CPU_Score"] = df["Processor"].apply(get_cpu_score)

df[["Processor", "CPU_Score"]].head(15)

                   Processor  CPU_Score
0   Intel Core Ultra 9 285HX         10
1      Intel Core i9-14900HX         10
2       Intel Core I5-13420H          6
3          Intel Core 7 240H          8
4          Intel Core 9 270H         10
5          Intel Core 7 240H          8
6          Intel Core 7 240H          8
7     Intel® Core™ i7-13620H          8
8    Intel® Core™ i7-14700HX          8
9     Intel® Core™ i7-13620H          8
10   Intel® Core™ i5-12450HX          6
11   Intel® Core™ i5-14450HX          6
12   Intel® Core™ i5-14450HX          6
13    Intel® Core™ i5-13420H          6
14    Intel® Core™ i5-13420H          6

In [66]:
def get_gpu_score(gpu):
    gpu = str(gpu).upper()

    match = re.search(r'(RTX|GTX).*?(\d{4})', gpu)

    if match:
        model = int(match.group(2))

        if model >= 5090:
            return 10
        elif model >= 5080:
            return 9.5
        elif model >= 5070:
            return 9
        elif model >= 5060:
            return 8.5
        elif model >= 5050:
            return 8
        elif model >= 4090:
            return 9.5
        elif model >= 4080:
            return 9
        elif model >= 4070:
            return 8.5
        elif model >= 4060:
            return 8
        elif model >= 4050:
            return 7
        elif model >= 3070:
            return 7
        elif model >= 3060:
            return 6.5
        elif model >= 3050:
            return 6
        elif model >= 2050:
            return 5
        elif model >= 1650:
            return 4
        elif model >= 1050:
            return 3

    if "ARC" in gpu:
        return 4

    elif "RADEON" in gpu:
        return 4

    elif "IRIS XE" in gpu:
        return 2

    elif "IRIS" in gpu:
        return 2

    elif "UHD" in gpu:
        return 1.5

    elif "INTEL HD" in gpu:
        return 1

    return 2


df["GPU_Score"] = df["GPU"].apply(get_gpu_score)

df[["GPU", "GPU_Score"]].head(20)

                                     GPU  GPU_Score
0           Nvidia GeForce RTX 5090 24GB       10.0
1            Nvidia GeForce RTX 5070 8GB        9.0
2            Nvidia GeForce RTX 4050 6GB        7.0
3         NVIDIA(R) GeForce RTX(TM) 5050        8.0
4            Nvidia GeForce RTX 5060 8GB        8.5
5                Nvidia GeForce RTX 5060        8.5
6                Nvidia GeForce RTX 5050        8.0
7              NVIDIA® GeForce RTX™ 3050        6.0
8              NVIDIA® GeForce RTX™ 4050        7.0
9              NVIDIA® GeForce RTX™ 4050        7.0
10           Nvidia GeForce RTX 3050 6GB        6.0
11             NVIDIA® GeForce RTX™ 3050        6.0
12             NVIDIA® GeForce RTX™ 3050        6.0
13             NVIDIA® GeForce RTX™ 3050        6.0
14             NVIDIA® GeForce RTX™ 3050        6.0
15             NVIDIA® GeForce RTX™ 5070        9.0
16             NVIDIA® GeForce RTX™ 5070        9.0
17             NVIDIA® GeForce RTX™ 5070        9.0
18  NVIDIA® GeForce RTX™ 5070 Laptop GPU        9.0
19             NVIDIA® GeForce RTX™ 5080        9.5

In [67]:
def get_resolution_score(resolution):
    resolution = str(resolution).upper()

    match = re.search(r'(\d+)\s*[X*]\s*(\d+)', resolution)

    if match:
        width = int(match.group(1))
        height = int(match.group(2))

        pixels = width * height

        if pixels >= 8000000:      # 4K+
            return 5
        elif pixels >= 4000000:    # QHD+/3K
            return 4
        elif pixels >= 2000000:    # Full HD
            return 3
        elif pixels >= 1000000:    # HD+
            return 2
        else:
            return 1

    return 2


df["Resolution_Score"] = df["Display_Resolution"].apply(get_resolution_score)

df[["Display_Resolution", "Resolution_Score"]].head(20)

   Display_Resolution  Resolution_Score
0           3840x2400                 5
1           2560*1440                 3
2           1920x1080                 3
3         2560 x 1600                 4
4         2560 x 1600                 4
5         2560 x 1600                 4
6         2560 x 1600                 4
7         1920 x 1080                 3
8         1920 x 1080                 3
9         1920 x 1080                 3
10        1920 x 1080                 3
11        1920 x 1080                 3
12       1920 x 1080)                 3
13        1920 x 1080                 3
14        1920 x 1080                 3
15        2560 x 1600                 4
16        2560 x 1600                 4
17          2560x1600                 4
18        2560 x 1600                 4
19          2560x1600                 4

In [68]:
df["Performance_Score"] = (
    (df["CPU_Score"] / 10 * 35) +
    (df["GPU_Score"] / 10 * 35) +
    (df["RAM_GB"].clip(upper=64) / 64 * 10) +
    (df["Storage_GB"].clip(upper=2048) / 2048 * 10) +
    (df["Resolution_Score"] / 5 * 5) +
    (df["Refresh_Hz"].clip(upper=240) / 240 * 5)
)

df["Performance_Score"] = df["Performance_Score"].round(2)

df[[
    "CPU_Score",
    "GPU_Score",
    "RAM_GB",
    "Storage_GB",
    "Resolution_Score",
    "Refresh_Hz",
    "Performance_Score"
]].head(10)

,CPU_Score,GPU_Score,RAM_GB,Storage_GB,Resolution_Score,Refresh_Hz,Performance_Score
0,10,10.0,96,10240,5,120,97.50
1,10,9.0,16,1024,3,165,80.44
2,6,7.0,8,512,3,144,55.25
3,8,8.0,16,512,4,120,67.50
4,10,8.5,16,1024,4,120,78.75
5,8,8.5,32,1024,4,120,74.25
6,8,8.0,16,1024,4,120,70.00
7,8,6.0,16,512,3,144,60.00
8,8,7.0,16,512,3,144,63.50
9,8,7.0,16,512,3,144,63.50

In [69]:
df[["Brand", "Price", "Performance_Score"]].sort_values(
    by="Performance_Score",
    ascending=False
).head(10)

    Brand   Price  Performance_Score
0     MSI  320000              97.50
56    MSI  299999              97.50
28    MSI  249999              97.50
58   ASUS  193999              97.25
152  ASUS  189999              97.25
150  ASUS  204999              97.25
274   MSI  229999              95.75
118   MSI  229999              92.50
198   MSI  176499              92.25
391  ASUS  146499              92.25

In [74]:
df.to_csv("laptops_Featured.csv", index=False)
print("Feature Engineering Completed Successfully!")

Feature Engineering Completed Successfully!

In [71]:
df[[
    "Brand",
    "Processor",
    "GPU",
    "Performance_Score"
]].sort_values(
    by="Performance_Score",
    ascending=False
).head(10)

,Brand,Processor,GPU,Performance_Score
0,MSI,Intel Core Ultra 9 285HX,Nvidia GeForce RTX 5090 24GB,97.50
56,MSI,Intel Core Ultra 9 285HX,Nvidia GeForce RTX™ 5090,97.50
28,MSI,Intel Core Ultra 9 285HX,Nvidia GeForce RTX 5090 24GB,97.50
58,ASUS,Intel Core Ultra 9 275HX,Nvidia GeForce RTX 5080,97.25
152,ASUS,Intel Core Ultra 9 285H,Nvidia GeForce RTX 5080 16GB,97.25
150,ASUS,Intel Core Ultra 9 275HX,Nvidia GeForce RTX 5080 16GB,97.25
274,MSI,Intel® Core™ i9-14900HX,NVIDIA® GeForce RTX™ 4090,95.75
118,MSI,Intel® Core™ Ultra 9 275HX,NVIDIA® GeForce RTX™ 5090 Laptop GPU,92.50
198,MSI,Intel Core i9-14900HX,NVIDIA® GeForce RTX™ 4090,92.25
391,ASUS,Intel core I9-13980HX,NVIDIA® GeForce RTX™ 4090 16GB,92.25

In [72]:
#Performance score is calculated

In [73]:
print(df["Performance_Score"].isna().sum())

0